export interface AiFeatureVector {
  symbol: string;
  timeframe: string;
  generatedAt: number;
  strategyAction: "EXECUTE" | "WAIT" | "REJECT";
  strategyId: string | null;
  strategyScore: number;
  strategyConfidence: number;
  strategyEdge: number;
  regime: string;
  regimeConfidence: number;
  signalDecision: string;
  signalConfidence: number;
  signalDirectionalEdge: number;
  signalAccepted: boolean;
  riskApproved: boolean;
  approvedRiskPercent: number;
  approvedRiskAmount: number;
  positionSize: number;
  projectedMarginUsagePercent: number;
  projectedOpenRiskPercent: number;
  analysisScore: number;
  dataQuality: number;
  volatilityPercent: number;
  trend: string;
  structure: string;
  mtfBias: string | null;
  mtfConfidence: number;
  atr: number | null;
  rsi: number | null;
  adx: number | null;
  macdHistogram: number | null;
  stochasticK: number | null;
  stochasticD: number | null;
  warmupComplete: boolean;
  orderRiskReward: number;
  spreadWarningCount: number;
  rejectionCount: number;
  backtestTradeCount: number;
  backtestWinRatePercent: number;
  backtestProfitFactor: number;
  backtestMaxDrawdownPercent: number;
  recentTradeCount: number;
  recentWinRatePercent: number;
  recentProfitFactor: number;
  recentAverageRMultiple: number;
  recentConsecutiveLosses: number;
}
