import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Grid, MenuItem, Stack, TextField, Typography } from "@mui/material";
import PlayArrowRounded from "@mui/icons-material/PlayArrowRounded";
import type { BacktestResultDto, BacktestRunRequest } from "../types";
import { runBacktest } from "../api";
import { MetricCard } from "../ui/MetricCard";
import { Sparkline } from "../ui/Sparkline";
import { money, percent } from "../format";

const initial: BacktestRunRequest={symbol:"XAUUSD",timeframe:"M15",from:"2025-01-01",to:"2025-12-31",initialBalance:10000,riskPercent:1,spread:.2,slippageTicks:2,intrabarPriority:"STOP_FIRST"};
export function BacktestPage(){const [input,setInput]=useState(initial);const [result,setResult]=useState<BacktestResultDto|null>(null);const [running,setRunning]=useState(false);const [error,setError]=useState<string|null>(null);async function submit(e:React.FormEvent){e.preventDefault();setRunning(true);setError(null);try{setResult(await runBacktest(input))}catch(err){setError(err instanceof Error?err.message:"Backtest failed") }finally{setRunning(false)}}return <Stack spacing={2}><Box><Typography variant="overline" color="primary" fontWeight={800}>PACK 10</Typography><Typography variant="h5" fontWeight={800}>Backtest Workbench</Typography><Typography variant="body2" color="text.secondary" sx={{mt:1}}>Endpoint sử dụng @xauusd/backtest-engine, không trả số liệu giả từ UI.</Typography></Box><Card><CardContent component="form" onSubmit={submit}><Grid container spacing={2}><Field label="Symbol" value={input.symbol} onChange={v=>setInput({...input,symbol:v.toUpperCase()})}/><SelectField label="Timeframe" value={input.timeframe} options={["M5","M15","M30","H1","H4"]} onChange={v=>setInput({...input,timeframe:v})}/><Field type="date" label="Từ ngày" value={input.from} onChange={v=>setInput({...input,from:v})}/><Field type="date" label="Đến ngày" value={input.to} onChange={v=>setInput({...input,to:v})}/><NumberField label="Vốn" value={input.initialBalance} onChange={v=>setInput({...input,initialBalance:v})}/><NumberField label="Risk %" value={input.riskPercent} step={.1} onChange={v=>setInput({...input,riskPercent:v})}/><NumberField label="Spread" value={input.spread} step={.01} onChange={v=>setInput({...input,spread:v})}/><SelectField label="Intrabar" value={input.intrabarPriority} options={["STOP_FIRST","OHLC_PATH"]} onChange={v=>setInput({...input,intrabarPriority:v as "STOP_FIRST"|"OHLC_PATH"})}/></Grid><Button type="submit" variant="contained" startIcon={<PlayArrowRounded/>} disabled={running} sx={{mt:2}}>{running?"Đang chạy...":"Chạy Pack 10"}</Button></CardContent></Card>{error?<Alert severity="error">{error}</Alert>:null}{result?<Result result={result}/>:null}</Stack>}
function Result({result}:{result:BacktestResultDto}){const m=result.metrics;return <Stack spacing={2}><Grid container spacing={2}><Grid size={{xs:12,sm:6,xl:3}}><MetricCard label="Net return" value={percent(m.netReturnPercent)} detail={money(m.netProfit)} tone={m.netProfit>=0?"success.main":"error.main"}/></Grid><Grid size={{xs:12,sm:6,xl:3}}><MetricCard label="Profit factor" value={m.profitFactor.toFixed(2)} detail={`${m.totalTrades} trades`}/></Grid><Grid size={{xs:12,sm:6,xl:3}}><MetricCard label="Win rate" value={percent(m.winRatePercent)} detail={`Expectancy ${money(m.expectancy)}`}/></Grid><Grid size={{xs:12,sm:6,xl:3}}><MetricCard label="Max drawdown" value={percent(m.maxDrawdownPercent)} detail={`Sharpe ${m.sharpeRatio.toFixed(2)}`} tone="error.main"/></Grid></Grid><Grid container spacing={2}><Grid size={{xs:12,xl:6}}><Card><CardContent><Typography fontWeight={800}>Equity</Typography><Sparkline values={result.equityCurve.map(p=>p.equity)} positive={m.netProfit>=0}/></CardContent></Card></Grid><Grid size={{xs:12,xl:6}}><Card><CardContent><Typography fontWeight={800}>Drawdown</Typography><Sparkline values={result.drawdownCurve.map(p=>p.drawdownPercent)} positive={false}/></CardContent></Card></Grid></Grid>{result.warnings.length?<Alert severity="warning">{result.warnings.join(" ")}</Alert>:null}</Stack>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <Grid size={{xs:12,sm:6,xl:3}}><TextField fullWidth size="small" label={label} type={type} value={value} onChange={(e: React.ChangeEvent<HTMLInputElement>)=>onChange(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/></Grid>}
function NumberField({label,value,onChange,step=1}:{label:string;value:number;onChange:(v:number)=>void;step?:number}){return <Grid size={{xs:12,sm:6,xl:3}}><TextField fullWidth size="small" label={label} type="number" value={value} onChange={(e: React.ChangeEvent<HTMLInputElement>)=>onChange(Number(e.target.value))} slotProps={{htmlInput:{step}}}/></Grid>}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <Grid size={{xs:12,sm:6,xl:3}}><TextField select fullWidth size="small" label={label} value={value} onChange={(e: React.ChangeEvent<HTMLInputElement>)=>onChange(e.target.value)}>{options.map(o=><MenuItem key={o} value={o}>{o}</MenuItem>)}</TextField></Grid>}
