import { Box, Card, CardContent, Grid, LinearProgress, Stack, Typography } from "@mui/material";
import { useDashboard } from "../hooks";
import { money, percent } from "../format";
import { MetricCard } from "../ui/MetricCard";
import { ErrorState, LoadingState } from "../ui/PageState";
import { StatusChip } from "../ui/StatusChip";

export function RiskPage(){const q=useDashboard();if(q.isLoading)return <LoadingState/>;if(!q.data)return <ErrorState message="Không có Risk snapshot."/>;const r=q.data.risk;return <Stack spacing={2}><Box><Typography variant="overline" color="primary" fontWeight={800}>PACK 06</Typography><Typography variant="h5" fontWeight={800}>Risk Engine</Typography><Typography variant="body2" color="text.secondary" sx={{mt:1}}>Risk Engine là nguồn phê duyệt duy nhất trước Strategy/Execution.</Typography></Box><Stack direction="row" justifyContent="flex-end"><StatusChip value={r.approved?"APPROVED":"BLOCKED"}/></Stack><Grid container spacing={2}><Grid size={{xs:12,sm:6,xl:3}}><MetricCard label="Risk / trade" value={percent(r.riskPercent)} detail={money(r.riskAmount)}/></Grid><Grid size={{xs:12,sm:6,xl:3}}><MetricCard label="Position size" value={`${r.positionSize.toFixed(2)} lot`} detail="normalized by Risk Engine"/></Grid><Grid size={{xs:12,sm:6,xl:3}}><MetricCard label="Margin usage" value={percent(r.marginUsagePercent)} detail="projected"/></Grid><Grid size={{xs:12,sm:6,xl:3}}><MetricCard label="Rejections" value={String(r.rejectionCodes.length)} detail={r.rejectionCodes[0]??"Không có"}/></Grid></Grid><Card><CardContent><Typography fontWeight={800}>Account limits</Typography><Grid container spacing={3} sx={{mt:1}}><Limit label="Daily loss" value={r.dailyLossPercent} max={r.maxDailyLossPercent}/><Limit label="Drawdown" value={r.drawdownPercent} max={r.maxDrawdownPercent}/><Limit label="Open risk" value={r.openRiskPercent} max={r.maxOpenRiskPercent}/></Grid></CardContent></Card></Stack>}
function Limit({label,value,max}:{label:string;value:number;max:number}){return <Grid size={{xs:12,md:4}}><Stack direction="row" justifyContent="space-between"><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="caption">{percent(value)} / {percent(max)}</Typography></Stack><LinearProgress variant="determinate" value={max>0?Math.min(100,value/max*100):0} color={max>0&&value/max>.8?"error":"success"} sx={{mt:1,height:7,borderRadius:10}}/></Grid>}
