import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Grid, Stack, Typography } from "@mui/material";
import LockRounded from "@mui/icons-material/LockRounded";
import { useQueryClient } from "@tanstack/react-query";
import { setTradingMode } from "../api";
import { useDashboard } from "../hooks";
import { ErrorState, LoadingState } from "../ui/PageState";
import { StatusChip } from "../ui/StatusChip";

export function SettingsPage(){const q=useDashboard();const qc=useQueryClient();const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);if(q.isLoading)return <LoadingState/>;if(!q.data)return <ErrorState message="Không có control state."/>;async function change(mode:"SHADOW"|"DEMO"){setSaving(true);setMessage(null);try{await setTradingMode(mode);await qc.invalidateQueries({queryKey:["dashboard-snapshot"]});setMessage(mode==="SHADOW"?"Đã khóa execution về SHADOW.":"Đã bật DEMO mode. Live vẫn khóa.")}catch(e){setMessage(e instanceof Error?e.message:"Không thể đổi mode.")}finally{setSaving(false)}}return <Stack spacing={2}><Box><Typography variant="overline" color="primary" fontWeight={800}>SAFETY CONTROL</Typography><Typography variant="h5" fontWeight={800}>Trading mode</Typography><Typography variant="body2" color="text.secondary" sx={{mt:1}}>Chỉ SHADOW và DEMO có API thay đổi. LIVE_LOCKED không có endpoint mở khóa.</Typography></Box><Stack direction="row" justifyContent="flex-end"><StatusChip value={q.data.control.mode}/></Stack>{message?<Alert severity="info">{message}</Alert>:null}<Grid container spacing={2}><Mode title="SHADOW" text="Pipeline phân tích đầy đủ nhưng không gửi lệnh." active={q.data.control.mode==="SHADOW"} onClick={()=>void change("SHADOW")} disabled={saving}/><Mode title="DEMO" text="Cho phép demo/simulated execution ở tầng sau; không phải tài khoản thật." active={q.data.control.mode==="DEMO"} onClick={()=>void change("DEMO")} disabled={saving}/><Grid size={{xs:12,md:4}}><Card sx={{height:"100%",opacity:.65}}><CardContent><LockRounded color="primary"/><Typography fontWeight={800} sx={{mt:2}}>LIVE LOCKED</Typography><Typography variant="body2" color="text.secondary" sx={{mt:1}}>Không thể mở trong Pack 12. Cần quy trình riêng của Pack 09.</Typography><Button disabled fullWidth variant="outlined" sx={{mt:3}}>Locked</Button></CardContent></Card></Grid></Grid></Stack>}
function Mode({title,text,active,onClick,disabled}:{title:string;text:string;active:boolean;onClick:()=>void;disabled:boolean}){return <Grid size={{xs:12,md:4}}><Card sx={{height:"100%",borderColor:active?"primary.main":undefined}}><CardContent><Typography fontWeight={800}>{title}</Typography><Typography variant="body2" color="text.secondary" sx={{mt:1,minHeight:48}}>{text}</Typography><Button onClick={onClick} disabled={disabled||active} fullWidth variant={active?"contained":"outlined"} sx={{mt:3}}>{active?"Đang sử dụng":"Chuyển mode"}</Button></CardContent></Card></Grid>}
